namespace agents_tools.controllers;

using System.Text;
using agents_tools.models;

public static class MarkdownGenerator
{
    private static string Quote(string value)
        => "\"" + (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    public static string GenerateAgentMarkdown(AgentManifest agent)
    {
        var sb = new StringBuilder();
        var description = string.IsNullOrWhiteSpace(agent.Description) ? agent.Name : agent.Description;
        sb.AppendLine("---");
        sb.AppendLine($"name: {Quote(agent.Name)}");
        sb.AppendLine($"description: {Quote(description)}");
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"# {agent.Name}");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(agent.Description)) sb.AppendLine(agent.Description + "\n");
        sb.AppendLine("## Metadata");
        sb.AppendLine();
        sb.AppendLine($"- Id: {agent.Id}");
        if (!string.IsNullOrWhiteSpace(agent.Category)) sb.AppendLine($"- Category: {agent.Category}");
        if (agent.SupportedActions?.Count > 0)
        {
            sb.AppendLine("- Supported Actions:");
            foreach (var a in agent.SupportedActions)
            {
                sb.AppendLine($"  - {a}");
            }
        }
        if (agent.ToolIds?.Count > 0)
        {
            sb.AppendLine("- Tool IDs:");
            foreach (var t in agent.ToolIds)
            {
                sb.AppendLine($"  - {t}");
            }
        }

        if (agent.Handoffs?.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("## Handoffs");
            foreach (var h in agent.Handoffs)
            {
                sb.AppendLine($"- To: {h.ToAgentId} - {h.Reason}");
            }
        }

        sb.AppendLine();
        sb.AppendLine("<!-- Generated by robots agents_tools -->");
        return sb.ToString();
    }

    public static string GenerateToolMarkdown(ToolManifest tool)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {tool.Name}");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(tool.Description)) sb.AppendLine(tool.Description + "\n");
        sb.AppendLine("## Capabilities");
        sb.AppendLine();
        foreach (var c in tool.Capabilities ?? new List<string>())
        {
            sb.AppendLine($"- {c}");
        }

        if (tool.Commands?.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("## Commands");
            foreach (var cmd in tool.Commands)
            {
                sb.AppendLine($"- {cmd}");
            }
        }

        sb.AppendLine();
        sb.AppendLine("<!-- Generated by robots agents_tools -->");
        return sb.ToString();
    }
}
